conn_postgresql:
  user: mgianotti
  password: U52DeTP8r8OfWfdyIEEMFkRuKIH8VXRG
  host: 10.100.114.248
  port: 5432
  database: warehouse

conn_mongo:
  id: datalec-warehouse-npd
  pwd: LqCUnp2m3ullSZrvSpQkbXgRYoEkNr3a
  server: "@sue-oms-prd-shard-00-03-pri.amewh.gcp.mongodb.net"
  port: 27017
  database: sue-oms-order-api
  collection: promiseOrder

table_schema: "dev.qal_omsorder_promiseorder"

table_name: qal_omsorder_promiseorder


